apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-demo
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo-app
              image: europe-west1-docker.pkg.dev/k8s-k3s-406521/k8s-repo/demo:v1.0.0
          restartPolicy: OnFailure
