---
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod-demo
spec:
  containers:
  - name: demo-app-v1
    image: europe-west1-docker.pkg.dev/k8s-k3s-406521/k8s-repo/demo:v1.0.0
  - name: demo-app-v2
    image: europe-west1-docker.pkg.dev/k8s-k3s-406521/k8s-repo/demo:v2.0.0
    command:
    - sleep
    - "3600"
