---
apiVersion: v1
kind: Pod
metadata:
  name: volume-mount-demo
spec:
  containers:
  - name: demo-app
    image: europe-west1-docker.pkg.dev/k8s-k3s-406521/k8s-repo/demo:v1.0.0
    volumeMounts:
    - name: data-volume
      mountPath: /data
      readOnly: true
    - name: config-volume
      mountPath: /config
      readOnly: false
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: my-pvc
  - name: config-volume
    configMap:
      name: configmap-demo
